export const TIMELINE_TEXT = {
  heading: '# タイムライン',
  empty: '(まだ記録がありません)',
  questionPrefixInitial: '**[初期反映]**',
  questionPrefix: '**Q**',
  questionPrefixFailed: '**[failed]**',
  metaSeparator: '・',
  aiGuessLabel: 'AI推定',
  proposedLabel: '提案',
  statusAnswered: '→ ✓ 反映済み',
  statusSkipped: '→ — スキップ',
  statusOpen: '→ ○ 未回答',
  statusFailed: '→ ✗ 反映失敗',
  failureReasonLabel: 'failureReason',
  attemptedAnswerLabel: 'attemptedAnswer',
  attemptedSkipLabel: 'attemptedSkip',
  sectionMarker: (title: string, timestamp: string) => `\n─── ${title} ─── *${timestamp}*`,
  manualEditHeading: '## Manual Edit',
}
