export const UI_TEXT = {
  app: {
    name: 'pre-spec',
    tagline: 'Spec Interview Workbench',
    downloadAll: '📥',
    generateTimelineError: '質問の生成に失敗しました。APIキーを確認してください。',
    retryQuestionError: '質問の作り直しに失敗しました。元の質問はそのまま残ります。',
  },

  startScreen: {
    openWorkFile: '作業ファイルを開く',
    openWorkFileLoading: '読み込み中…',
    openWorkFileError: '作業ファイルの読み込みに失敗しました。ファイル形式を確認してください。',
    openWorkFileNameError: 'ファイル名の形式が正しくありません。{projectSlug}.pre-spec.json を選択してください。',
    newProject: '新規作成',
    projectNameLabel: 'プロジェクト名',
    projectNamePlaceholder: '例: user-auth-feature',
    projectNameRequired: 'プロジェクト名を入力してください',
    projectNameInvalid: 'プロジェクト名には英数字が必要です（例: my-feature）',
    requirementMemoLabel: '仕様化したい要件定義メモ',
    requirementMemoFileButton: '📤',
    requirementMemoFileSelected: (name: string) => `選択中: ${name}`,
    requirementMemoRequired: 'ファイルを選択してください',
    relatedLabel: '関連資料（任意）',
    relatedAddButton: '+ 追加',
    relatedFileMode: 'ファイル',
    relatedUrlMode: 'URL',
    relatedFileButton: '📤',
    relatedFileSelected: (name: string) => `選択中: ${name}`,
    relatedUrlPlaceholder: 'https://',
    relatedNotePlaceholder: '一言補足',
    relatedRemoveButton: '✕',
    startButton: '開始',
    startButtonLoading: '開始中…',
    backButton: '戻る',
    filenamePreview: (slug: string) => `ファイル名: ${slug}.pre-spec.json`,
  },

  specEditor: {
    fileLabel: 'spec.md',
    previewButton: 'Preview',
    sourceButton: 'Source',
    editButton: 'Edit',
    saveButton: '保存して戻る',
    cancelButton: 'キャンセル',
    editModeNote:
      '直接編集モードです。この編集は質問への回答ではなく、manual_edit としてタイムラインに記録されます。',
    memoPlaceholder: '編集メモ (任意)',
  },

  manualEdit: {
    label: 'spec.md を手動編集しました',
    affected: 'affected',
    memo: 'memo',
  },

  bottomTabs: {
    memoTab: 'References',
    addRefButton: '+ 追加',
    addRefFile: 'ファイル',
    addRefUrl: 'URL',
    addRefUrlPlaceholder: 'https://',
    addRefNotePlaceholder: 'note',
    addRefFileButton: '📤',
    addRefAddButton: '追加',
    addRefReviewing: '確認中…',
    addRefUnreadable: (reason: string) => `読み込み不可: ${reason}`,
    addRefError: '確認に失敗しました',
  },

  interview: {
    nextButton: '次へ →',
    addQuestionsButton: '+ 質問を追加',
    addQuestionsLoading: '生成中…',
    openQuestionsWarning:
      '未回答の質問があります。先に回答するか、スキップして未決事項として残してください。',
    formattingFallbackWarning: '整形に失敗しました。回答をそのまま反映しました。',
    timelineEmpty: '質問タイムラインがまだ生成されていません',
    timelineEmptyHint: '「+ 質問を追加」で生成してください',
    sectionNotFound: 'セクションが見つかりません',
    aiGuessLabel: 'AI推定',
    answerPlaceholder: '回答を入力…',
    answerButton: '回答して反映',
    answerButtonFormatting: '整形中…',
    retryButton: '↻',
    retryButtonTitle: '質問を作り直す',
    skipButton: 'スキップ ▾',
    skipReasonLabel: 'スキップ理由',
    skipCustomPlaceholder: '理由を入力（必須）',
    skipConfirmButton: 'スキップして記録',
    skipCancelButton: '戻る',
    statusAnswered: '✓',
    statusSkipped: '—',
    statusOpen: '○',
    statusFailed: '✗',
    failedBadge: '反映失敗',
    failedReason: 'セクションが見つかりません',
  },

  preflight: {
    title: '出力前チェック',
    downloadConfirmTitle: '出力前チェック',
    downloadConfirmOpenQuestions: (n: number) => `未回答の質問: ${n}件`,
    downloadConfirmMarkerHeader: 'marker:',
    downloadConfirmMarkerItem: (name: string, n: number) => `  - ${name}: ${n}件`,
    downloadConfirmWarning: '未回答の質問 または marker が残っています。',
    downloadConfirmPrompt: 'この状態で成果物を出力しますか？',
  },

  initialConfirmation: {
    phaseLabel: 'Initial Setup',
    proposedMarkdownLabel: '提案 Markdown',
    answerPlaceholder: 'OK / このままでよい / 以下のように修正…',
    applyNote: 'この内容を反映します',
    generationError: '初期反映質問の生成に失敗しました',
  },

}
